/**
 * Planet archetypes: which biomes a world draws from, its oceans, climate,
 * atmosphere and weather. The generator (system.ts) jitters every value per
 * planet, so two worlds of one archetype never look alike.
 */

export type Archetype =
  | 'terran'
  | 'jungle'
  | 'ocean'
  | 'desert'
  | 'arid'
  | 'frozen'
  | 'taiga'
  | 'volcanic'
  | 'barren'
  | 'rust'
  | 'alien'
  | 'toxic'
  | 'gas'
  | 'iceGiant';

export type WaterKind = 'none' | 'water' | 'lava' | 'ice' | 'acid';

export interface ArchetypeSpec {
  label: string;
  biomes: string[];
  biomeCount: [number, number];
  /** Fraction of the surface below sea level (0 = no oceans). */
  sea: [number, number];
  water: WaterKind;
  /** Shallow and deep liquid colours (sRGB). */
  shallow: number;
  deep: number;
  /** Equatorial temperature and global moisture, 0..1. */
  temperature: [number, number];
  moisture: [number, number];
  /** Atmosphere column density relative to Earth (0 = airless). */
  air: [number, number];
  /** Rayleigh scattering colour weights (Earth ≈ 0.18, 0.42, 1). */
  rayleigh: [number, number, number];
  /** Mie (haze) strength and colour. */
  haze: number;
  hazeColor: number;
  clouds: [number, number];
  cloudColor: number;
  /** Mean relief multiplier. */
  relief: [number, number];
  /** Where in a system the archetype forms: 0 hot inner … 1 cold outer. */
  zone: [number, number];
  weight: number;
}

export const ARCHETYPES: Record<Archetype, ArchetypeSpec> = {
  terran: {
    label: 'Temperate world',
    biomes: [
      'meadow',
      'forest',
      'taiga',
      'alpine',
      'savanna',
      'jungle',
      'swamp',
      'tundra',
      'autumn',
      'steppe',
      'blossom',
      'snowfields',
      'dunes',
      'cliffs',
    ],
    biomeCount: [6, 8],
    sea: [0.45, 0.68],
    water: 'water',
    shallow: 0x2a9db0,
    deep: 0x0a2a52,
    temperature: [0.55, 0.75],
    moisture: [0.5, 0.75],
    air: [0.9, 1.15],
    rayleigh: [0.18, 0.42, 1],
    haze: 0.25,
    hazeColor: 0xdfe6ee,
    clouds: [0.38, 0.62],
    cloudColor: 0xffffff,
    relief: [0.9, 1.2],
    zone: [0.3, 0.6],
    weight: 22,
  },
  jungle: {
    label: 'Jungle world',
    biomes: [
      'jungle',
      'swamp',
      'mushroom',
      'meadow',
      'tropicalIsles',
      'forest',
      'blossom',
      'cliffs',
    ],
    biomeCount: [5, 7],
    sea: [0.3, 0.5],
    water: 'water',
    shallow: 0x2aa894,
    deep: 0x0a3a4a,
    temperature: [0.75, 0.92],
    moisture: [0.75, 0.95],
    air: [1.1, 1.5],
    rayleigh: [0.22, 0.48, 0.9],
    haze: 0.55,
    hazeColor: 0xd8e8d0,
    clouds: [0.55, 0.78],
    cloudColor: 0xf4f8f2,
    relief: [0.9, 1.3],
    zone: [0.3, 0.55],
    weight: 12,
  },
  ocean: {
    label: 'Ocean world',
    biomes: ['tropicalIsles', 'cliffs', 'jungle', 'meadow', 'blossom', 'swamp'],
    biomeCount: [3, 5],
    sea: [0.82, 0.92],
    water: 'water',
    shallow: 0x3ac8c8,
    deep: 0x062a5a,
    temperature: [0.6, 0.85],
    moisture: [0.7, 0.9],
    air: [1, 1.3],
    rayleigh: [0.16, 0.42, 1],
    haze: 0.3,
    hazeColor: 0xe4eef6,
    clouds: [0.45, 0.7],
    cloudColor: 0xffffff,
    relief: [1, 1.4],
    zone: [0.35, 0.6],
    weight: 10,
  },
  desert: {
    label: 'Desert world',
    biomes: [
      'dunes',
      'redCanyons',
      'mesas',
      'saltFlats',
      'badlands',
      'cactusScrub',
      'blackDunes',
      'boneDesert',
    ],
    biomeCount: [5, 7],
    sea: [0, 0.1],
    water: 'water',
    shallow: 0x3ab0a8,
    deep: 0x1a5a6a,
    temperature: [0.75, 0.95],
    moisture: [0.02, 0.25],
    air: [0.6, 1],
    rayleigh: [0.42, 0.42, 0.6],
    haze: 0.75,
    hazeColor: 0xf0d8b0,
    clouds: [0.02, 0.15],
    cloudColor: 0xfff4e4,
    relief: [0.9, 1.3],
    zone: [0.1, 0.45],
    weight: 14,
  },
  arid: {
    label: 'Savanna world',
    biomes: [
      'savanna',
      'steppe',
      'badlands',
      'mesas',
      'cactusScrub',
      'dunes',
      'meadow',
      'redCanyons',
    ],
    biomeCount: [5, 7],
    sea: [0.15, 0.35],
    water: 'water',
    shallow: 0x46b4a0,
    deep: 0x0e3a5a,
    temperature: [0.68, 0.88],
    moisture: [0.2, 0.45],
    air: [0.8, 1.1],
    rayleigh: [0.26, 0.42, 0.85],
    haze: 0.45,
    hazeColor: 0xeee0c8,
    clouds: [0.15, 0.35],
    cloudColor: 0xffffff,
    relief: [0.8, 1.2],
    zone: [0.2, 0.5],
    weight: 10,
  },
  frozen: {
    label: 'Frozen world',
    biomes: ['snowfields', 'glacier', 'iceSpires', 'frostPlains', 'tundra', 'alpine', 'taiga'],
    biomeCount: [5, 7],
    sea: [0.3, 0.5],
    water: 'ice',
    shallow: 0xb8dcef,
    deep: 0x6a9cc0,
    temperature: [0.02, 0.22],
    moisture: [0.3, 0.6],
    air: [0.4, 0.9],
    rayleigh: [0.14, 0.36, 1],
    haze: 0.35,
    hazeColor: 0xe0eef8,
    clouds: [0.2, 0.45],
    cloudColor: 0xf4f8ff,
    relief: [0.9, 1.3],
    zone: [0.65, 1],
    weight: 14,
  },
  taiga: {
    label: 'Boreal world',
    biomes: [
      'taiga',
      'tundra',
      'alpine',
      'autumn',
      'snowfields',
      'frostPlains',
      'forest',
      'glacier',
    ],
    biomeCount: [5, 7],
    sea: [0.35, 0.55],
    water: 'water',
    shallow: 0x3a8aa0,
    deep: 0x0a2440,
    temperature: [0.25, 0.45],
    moisture: [0.45, 0.7],
    air: [0.85, 1.1],
    rayleigh: [0.17, 0.4, 1],
    haze: 0.3,
    hazeColor: 0xe0e8ee,
    clouds: [0.35, 0.6],
    cloudColor: 0xffffff,
    relief: [1, 1.4],
    zone: [0.45, 0.75],
    weight: 10,
  },
  volcanic: {
    label: 'Volcanic world',
    biomes: ['lavaFields', 'ashPlains', 'obsidian', 'sulfur', 'blackDunes', 'basaltShelves'],
    biomeCount: [4, 6],
    sea: [0.2, 0.4],
    water: 'lava',
    shallow: 0xff7a20,
    deep: 0xa01a04,
    temperature: [0.85, 1],
    moisture: [0.2, 0.7],
    air: [0.6, 1.4],
    rayleigh: [0.5, 0.25, 0.18],
    haze: 0.9,
    hazeColor: 0x9a6a5a,
    clouds: [0.25, 0.5],
    cloudColor: 0x8a7a76,
    relief: [1.1, 1.5],
    zone: [0, 0.35],
    weight: 10,
  },
  barren: {
    label: 'Airless world',
    biomes: ['regolith', 'craterHighlands', 'basaltShelves', 'badlands'],
    biomeCount: [3, 4],
    sea: [0, 0],
    water: 'none',
    shallow: 0,
    deep: 0,
    temperature: [0.3, 0.7],
    moisture: [0.3, 0.7],
    air: [0, 0],
    rayleigh: [0.2, 0.4, 1],
    haze: 0,
    hazeColor: 0xffffff,
    clouds: [0, 0],
    cloudColor: 0xffffff,
    relief: [1, 1.4],
    zone: [0, 1],
    weight: 6,
  },
  rust: {
    label: 'Rust world',
    biomes: ['rustPlains', 'redCanyons', 'craterHighlands', 'blackDunes', 'mesas', 'frostPlains'],
    biomeCount: [4, 6],
    sea: [0, 0.08],
    water: 'ice',
    shallow: 0xe0e8ee,
    deep: 0xb8c8d4,
    temperature: [0.3, 0.55],
    moisture: [0.05, 0.25],
    air: [0.2, 0.45],
    rayleigh: [0.6, 0.42, 0.3],
    haze: 0.8,
    hazeColor: 0xd8a070,
    clouds: [0.02, 0.1],
    cloudColor: 0xf0e0d0,
    relief: [1.1, 1.5],
    zone: [0.4, 0.8],
    weight: 10,
  },
  alien: {
    label: 'Exotic biosphere',
    biomes: [
      'crystalFields',
      'glowForest',
      'violetPrairie',
      'coralHighlands',
      'mushroom',
      'blossom',
      'iceSpires',
    ],
    biomeCount: [5, 7],
    sea: [0.3, 0.55],
    water: 'water',
    shallow: 0x8a5ad8,
    deep: 0x1a0a4a,
    temperature: [0.45, 0.75],
    moisture: [0.45, 0.85],
    air: [0.8, 1.3],
    rayleigh: [0.55, 0.22, 0.9],
    haze: 0.4,
    hazeColor: 0xe8c8f0,
    clouds: [0.25, 0.5],
    cloudColor: 0xf8eaff,
    relief: [1, 1.4],
    zone: [0.3, 0.7],
    weight: 14,
  },
  toxic: {
    label: 'Toxic world',
    biomes: ['toxicMarsh', 'sulfur', 'mushroom', 'boneDesert', 'ashPlains', 'glowForest'],
    biomeCount: [4, 6],
    sea: [0.25, 0.45],
    water: 'acid',
    shallow: 0x9adf2a,
    deep: 0x2a4a0a,
    temperature: [0.6, 0.85],
    moisture: [0.5, 0.9],
    air: [1.2, 1.8],
    rayleigh: [0.42, 0.6, 0.18],
    haze: 1,
    hazeColor: 0xc8d870,
    clouds: [0.35, 0.6],
    cloudColor: 0xd8e090,
    relief: [0.9, 1.3],
    zone: [0.2, 0.55],
    weight: 8,
  },
  gas: {
    label: 'Gas giant',
    biomes: [],
    biomeCount: [0, 0],
    sea: [0, 0],
    water: 'none',
    shallow: 0,
    deep: 0,
    temperature: [0.4, 0.6],
    moisture: [0.5, 0.5],
    air: [2.2, 3],
    rayleigh: [0.3, 0.42, 0.7],
    haze: 1,
    hazeColor: 0xe8d8c0,
    clouds: [1, 1],
    cloudColor: 0xffffff,
    relief: [1, 1],
    zone: [0.55, 1],
    weight: 18,
  },
  iceGiant: {
    label: 'Ice giant',
    biomes: [],
    biomeCount: [0, 0],
    sea: [0, 0],
    water: 'none',
    shallow: 0,
    deep: 0,
    temperature: [0.1, 0.3],
    moisture: [0.5, 0.5],
    air: [2.2, 3],
    rayleigh: [0.12, 0.45, 0.95],
    haze: 0.8,
    hazeColor: 0xd0f0f8,
    clouds: [1, 1],
    cloudColor: 0xf0ffff,
    relief: [1, 1],
    zone: [0.75, 1],
    weight: 10,
  },
};

export const ARCHETYPE_LIST = Object.keys(ARCHETYPES) as Archetype[];
export const isGiant = (a: Archetype) => a === 'gas' || a === 'iceGiant';
